server:
  port: 8081
spring:
  profiles:
    active: prod
  redis:
    database: 0
    # Redis服务器地址
    host: 192.168.4.30
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: doyd1913
    # 连接超时时间（毫秒）
    timeout: 10000ms
    lettuce:
      pool:
        min-idle: 2
        max-active: 30
        max-wait: 5000
        max-idle: 30